/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Penjualan.view;

import Penjualan.entity.Barang;
import Penjualan.interfc.barangInterface;
import com.sun.istack.internal.logging.Logger;
import java.util.*;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import penjualan.implement.implementBarang;

/**
 *
 * @author ASUS
 */
public class barangView extends javax.swing.JFrame {

    List <Barang> record = new ArrayList<Barang>();
    barangInterface brgServis;
    private int row;
   
    /**
     * Creates new form barangView
     */
    public barangView() {
        initComponents();
       
        brgServis = new implementBarang();
        tbl_barang.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                row = tbl_barang.getSelectedRow();
                if(row!=-1){
                    isiText();
                }
            }
        });
        this.statusAwal();
    }
    
    private void loadData(){
        try{
            record = brgServis.getAll();
        }catch(Exception e){
            Logger.getLogger(barangView.class).log(Level.SEVERE, null, e);
        }
    }
    
    private void isiTabel(){
        Object data[][] = new Object[record.size()][4];
        int x = 0;
        for(Barang barang : record){
            data[x][0] = barang.getKodeBarang();
            data[x][1] = barang.getNamaBarang();
            data[x][2] = barang.getJumlahBarang();
            data[x][3] = barang.getHargaBarang();
            x++;
        }
        String [] judul = {"kode barang", "nama barang", "Jumlah", "Harga"};
        tbl_barang.setModel(new DefaultTableModel(data, judul));
        jScrollPane1.setViewportView(tbl_barang);
    }
    
    private void isiText(){
        Barang barang = record.get(row);
        txt_kode.setText(barang.getKodeBarang());
        txt_nama.setText(barang.getNamaBarang());
        txt_jumlah.setText(String.valueOf(barang.getJumlahBarang()));
        txt_harga.setText(String.valueOf(barang.getHargaBarang()));
    }
    
    private void kosongkanText(){
        txt_kode.setText("");
        txt_nama.setText("");
        txt_jumlah.setText("");
        txt_harga.setText("");
    }
    private void statusAwal(){
        kosongkanText();
        loadData();
        isiTabel();
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        txt_tambah = new javax.swing.JButton();
        txt_edit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_barang = new javax.swing.JTable();
        txt_hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setText("Kode Barang");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Jumlah");

        jLabel4.setText("Harga");

        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jml(evt);
            }
        });

        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });

        txt_tambah.setBackground(new java.awt.Color(51, 255, 0));
        txt_tambah.setForeground(new java.awt.Color(255, 255, 255));
        txt_tambah.setText("Tambah");
        txt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tambahActionPerformed(evt);
            }
        });

        txt_edit.setBackground(new java.awt.Color(153, 0, 255));
        txt_edit.setForeground(new java.awt.Color(255, 255, 255));
        txt_edit.setText("Ubah");
        txt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_editActionPerformed(evt);
            }
        });

        tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Jumlah", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tbl_barang);

        txt_hapus.setBackground(new java.awt.Color(255, 51, 51));
        txt_hapus.setForeground(new java.awt.Color(255, 255, 255));
        txt_hapus.setText("Hapus");
        txt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_tambah)
                                .addGap(41, 41, 41)
                                .addComponent(txt_hapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_edit))
                            .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tambah)
                    .addComponent(txt_edit)
                    .addComponent(txt_hapus))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jml(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jml
        // TODO add your handling code here:
    }//GEN-LAST:event_jml

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void txt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tambahActionPerformed
        try{
            Barang barang = new Barang();
            barang.setKodeBarang(txt_kode.getText());
            barang.setNamaBarang(txt_nama.getText());
            barang.setJumlahBarang(Integer.valueOf(txt_jumlah.getText()));
            barang.setHargaBarang(Integer.valueOf(txt_harga.getText()));
            
            brgServis.insert(barang);
            this.statusAwal();
            JOptionPane.showMessageDialog(this, "Data Tersimpan");
        } catch(Exception ex){
            Logger.getLogger(barangView.class).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
        }   
        statusAwal();
    }//GEN-LAST:event_txt_tambahActionPerformed

    private void txt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_editActionPerformed
           try{
            Barang barang = new Barang();
            barang.setKodeBarang(txt_kode.getText());
            barang.setNamaBarang(txt_nama.getText());
            barang.setJumlahBarang(Integer.valueOf(txt_jumlah.getText()));
            barang.setHargaBarang(Integer.valueOf(txt_harga.getText()));
            
            brgServis.update(txt_kode.getText(), barang);
            this.statusAwal();
            JOptionPane.showMessageDialog(this, "Data Tersimpan");
        } catch(Exception ex){
            Logger.getLogger(barangView.class).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
        } 
    }//GEN-LAST:event_txt_editActionPerformed

    private void txt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hapusActionPerformed
         Barang barang = new Barang();
         String kode = txt_kode.getText();
         try{
            brgServis.delete(kode);
         }catch(Exception ex){
           Logger.getLogger(barangView.class).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(this, ex);       
         }
         this.statusAwal();
         JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
    }//GEN-LAST:event_txt_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barangView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_barang;
    private javax.swing.JButton txt_edit;
    private javax.swing.JButton txt_hapus;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JButton txt_tambah;
    // End of variables declaration//GEN-END:variables
}
